using Content.Shared.Imperial.Medieval.Cult;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Cult;

[GenerateTypedNameReferences]
public sealed partial class CultRuneMenuWindow : DefaultWindow
{
    public Action<ProtoId<CultRunePrototype>>? OnRuneCarve;

    public CultRuneMenuWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(CultRuneMenuBoundUserInterfaceState state)
    {
    }
}
